### DISCUSSION TITLE
Checkboxes not having ticks after publishing application

### DISCUSSION THREAD

**Discussion by Josh-Nicholson** [skeletonlabs/skeleton#1835] [Q&A]
I'm encountering an issue in production where checkboxes don't have any ticks.
They are there on dev, just not on the built version of the site.
The app is built using the node adapter.

When inspecting the UI using dev tools it states that the background-image is an 'Invalid property value' on checkbox:checked

Example
![image](https://github.com/skeletonlabs/skeleton/assets/9265897/91e32129-8d74-49a7-aa1f-833571c94a7e)
![image](https://github.com/skeletonlabs/skeleton/assets/9265897/1528c339-7c0c-4de2-b293-588643fd0f5a)

For reference here is the css value of my live site
``` css
[type=checkbox]:checked{background-image:url(data:image/svg+xml,%3csvg viewBox='0 0 16 16' fill='white' xmlns='http://www.w3.org/2000/svg'%3e%3cpath d='M12.207 4.793a1 1 0 010 1.414l-5 5a1 1 0 01-1.414 0l-2-2a1 1 0 011.414-1.414L6.5 9.086l4.293-4.293a1 1 0 011.414 0z'/%3e%3c/svg%3e)}
```

and here is the value from the live skeleton site:
``` css
[type=checkbox]:checked{background-image:url("data:image/svg+xml,%3csvg viewBox='0 0 16 16' fill='white' xmlns='http://www.w3.org/2000/svg'%3e%3cpath d='M12.207 4.793a1 1 0 010 1.414l-5 5a1 1 0 01-1.414 0l-2-2a1 1 0 011.414-1.414L6.5 9.086l4.293-4.293a1 1 0 011.414 0z'/%3e%3c/svg%3e")}
```
