### DISCUSSION TITLE
A new stroke-token?

### DISCUSSION THREAD

**Discussion by Marceltbn** [skeletonlabs/skeleton#2444] [Ideas]

**Comment by endigo9740** [comment]
Hey @Marceltbn, I'd definitely recommend checking this post regarding the [next major version of Skeleton](https://github.com/skeletonlabs/skeleton/discussions/2375). As part of this process we're implementing a lot of additions and updates to our Tailwind plugin and token classes.

That said, you should be able to handle this locally within your project for now. I've modified your snippet above. Drop this straight into your global stylesheet and it should work right away:

```css
.dark .stroke-token {
    stroke: rgba(var(--theme-font-color-dark));
}

.stroke-token { /* <--- fixed this */
    stroke: rgba(var(--theme-font-color-base));
}
```

You should then be able to use this token class anywhere you wish throughout the app:

```html
<svg class="stroke-token">...</svg>
```

Additionally I will put this on my list to double check per our upcoming v3 changes. I've already built a few really awesome updates that should greatly extend the theme settings AND the possible combinations of styles from Tailwind's utilities. But I'll verify this one specifically. You may see me reference this ticket in another thread for that.
