### ISSUE TITLE
Add labels to ticks in Range Slider

### ISSUE THREAD

**Issue by SebasF1349** [skeletonlabs/skeleton#1066]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Add labels to the ticks in the Range Slider component as shown in the pic below
![time-tracker-app_0t9zHvHm9P](https://user-images.githubusercontent.com/33849340/222016881-b021b5df-cf87-4c0b-8ff9-a374c2697723.png)

### What type of pull request would this be?

Enhancement

### Any links to similar examples or other references we should review?

[As discussed in Discord](https://discord.com/channels/1003691521280856084/1080268105974026250/1080268105974026250) this will require add some styles to the datalist and options.

[MDN documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range#adding_tick_marks)

Suggestion by Chris:

```
1. Create a new prop labels: boolean = false
2. Use <datalist class:labels={labels} to conditionally add a .labels class
3. Then locally (within the component) add a <style> tag and add the required classes there.
```

After some testing, I arrived to these styles that work in my case:

```css
.labels {
	display: flex;
	flex-direction: row;
	justify-content: space-between;
	padding-left: 0.1rem; <!-- This px was found by trial and error for my case, didn't found the exact value used for the ticks -->
	padding-right: 0.1rem; <!-- This px was found by trial and error for my case, didn't found the exact value used for the ticks -->
}
```
Also the `option` needs a `pt-1` to separate to the slider.

This creates the Range Slider in the pic at the top, but needs more testing.

Finally, it would probably be nice to add the option to add text labels for other use cases. Something like `labels: "none" | "numbers" | string[] = "none"`

If you want, I can work on this, test it and create a pr to review later this week.
