### ISSUE TITLE
Table region props not working as expected

### ISSUE THREAD

**Issue by samuel-odinware** [skeletonlabs/skeleton#1216]
### Current Behavior

When passing additional classes to the `Table` component, the result is not what I am expecting. This could be a lack of understanding of the documentation on my part but here is an example of the issue.

Code:

```javascript
<Table source={tableData} regionBody="bg-surface-800/60" />
```

Result:

```css
.bg-surface-800\/60 {
    background-color: rgb(var(--color-surface-800) / 0.6);
}
```

When changing the above style in the inspector from `.bg-surface-800\/60` to `.dark .table`, I get the expected result.
