### ISSUE TITLE
Update Themes doc to show how to overwrite preset theme values

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#1235]
### Link to the Page

https://www.skeleton.dev/docs/themes

### Describe the Issue

Per: https://discord.com/channels/1003691521280856084/1091037176864718848/1091037176864718848

---

General idea is a theme is just a set of CSS Properties (aka variables), which means they can be overwritten later in scope. This means if you wanted to overwrite the font families for the Modern theme, you could drop this ins your `/src/app.postcss` file:

```css
:root {
    --theme-font-family-base: 'MyCustomFont', sans-serif;
    --theme-font-family-heading: 'MyCustomFont', sans-serif;
}
```

Let's update the documentation to show this process and explain that it can be used to change ANY theme property, not just fonts.

### Are you able to create a Pull Request with the fix?

Yes
