### ISSUE TITLE
Make scrollbar customization opt-in

### ISSUE THREAD

**Issue by hackape** [skeletonlabs/skeleton#1304]
### Current Behavior

On macOS the default behavior of scrollbar, when not CSS custsomized, is automatically shown during scrolling, and hidden after a delay when scrolling is done.

Skeleton applies scrollbar customization by default. Although `.hide-scrollbar` is provided as an opt-out escape, I find it **NOT** able to reset to default behavior described above.

It seems like when any `::-webkit-scrollbar {}` rule is applied, there's just no way to go back. I've tried CSS keyword value `unset` to override everything, yet the scrollbar stays either shown or hidden. But I really want the auto show/hide feature back.

I hope you can make scrollbar customization opt-in, so to resolve this issue.

### Steps To Reproduce

<no need>

**Comment by endigo9740** [comment]
The scroll behavior you're describing is default to macOS, like you mentioned. Skeleton does not, and cannot control that auto-hide behavior. That has to be adjusted at the OS level. The only thing Skeleton does it modify the visual style of the scrollbars. 

You can view the styles here:
https://github.com/skeletonlabs/skeleton/blob/dev/src/lib/styles/core.css#L27

If you wish to remove these, use the same selectors in your global stylesheet, and set `unset` on them:
https://developer.mozilla.org/en-US/docs/Web/CSS/unset

We have no current intentions to make these styles opt-in.

**Comment by hackape** [comment]
@Sarenor Yes, that is correct. I've tested on Chrome and Safari on MacOS. 

After the following `unset` rules, 1-to-1 corresponding to what is applied by skeleton, the scrollbar just disappears entirely.

```css
::-webkit-scrollbar {
	width: unset !important;
}
::-webkit-scrollbar-track {
	padding-left: unset !important;
	padding-right: unset !important;
	background-color: unset !important;
}
.dark ::-webkit-scrollbar-track {
	background-color: unset !important;
}
::-webkit-scrollbar-thumb {
	background-color: unset !important;
}
.dark ::-webkit-scrollbar-thumb {
	background-color: unset !important;
}
::-webkit-scrollbar-thumb {
	border-radius: unset !important;
}
```
