### ISSUE TITLE
Scrollbar customizations cause bug in Chrome on macOS

### ISSUE THREAD

**Issue by michenriksen** [skeletonlabs/skeleton#1356]
### Current Behavior

The customizations done to the scrollbar in [core.css](https://github.com/skeletonlabs/skeleton/blob/dev/src/lib/styles/core.css#L29-L46) causes the scrollbar “track” to always be visible and take up space from the content, instead of floating on top/overlay the content, inside elements with a defined height and `overflow-y-auto`. 

As an example, I have taken the [sticky position](https://tailwindcss.com/docs/position#sticky-positioning-elements) demo code from Tailwind's documentation and put it in a JSFiddle with Tailwind loaded: https://jsfiddle.net/x2vq8skn/

Notice how the scrollbar floats nicely on top/overlays the content on macOS Chrome:

![vanilla-tailwindcss-scrollbars](https://user-images.githubusercontent.com/304361/233832781-8d277a79-fd8b-48ce-9c71-6e7bf1fad7f5.gif)

If I generate a new Skeleton project and copy-paste the same demo code into `+page.svelte`, the scrollbar area is permanently visible, creating an ugly gap instead of overlaying the content:

![skeleton-scrollbars](https://user-images.githubusercontent.com/304361/233833036-a20933a9-09ea-47cc-98f9-d9e41a27b79b.gif)

### Reproduction / Steps To Reproduce

1. Generate a new Skeleton app with `npm create skeleton-app@latest my-skeleton-app` with default options.
2. Open `src/routes/+page.svelte` and replace content with HTML code from https://jsfiddle.net/x2vq8skn/
3. Run `npm run dev` and open the dev URL in Chrome on macOS. Notice that the scrollbar customizations cause the scrollbar area to always be visible instead of overlaying the content like in the JSFiddle demonstration.

### Anything else?

I am aware that this issue has been [reported and closed as `wont-fix`](https://github.com/skeletonlabs/skeleton/issues/1304); however, I'm opening this issue hoping you will reconsider your `wont-fix` decision. I think it looks awful, and could possibly be a show-stopper for many with the current behavior.

The workaround mentioned in #1304 unfortunately doesn't work. 

I'm sure there is a good reason you introduced the scrollbar customizations, so maybe @hackape's proposal to make it opt-in is a viable solution? If it's possible, having a `.no-scrollbar-customization` to add to elements when needed would also be a nice way to handle it!

**Comment by hackape** [comment]
FYI, my current workaround is to roll my own [`all.css`](https://github.com/skeletonlabs/skeleton/blob/dev/src/lib/styles/all.css). Since the scrollbar related bits are in [`core.css`](https://github.com/skeletonlabs/skeleton/blob/dev/src/lib/styles/core.css), just need to comment out those lines.

```css
/* Tailwind Directives */
@import 'tailwind.css';

/* Global Styles */
/* @import 'core.css'; */
@layer base {
	/* === Body Styles === */

	body {
		@apply bg-surface-50-900-token;
	}

	/* === Selection === */

	::selection {
		@apply bg-primary-500/30;
	}

	/* === Focus === */

	/* Outline (do not change) */
	/* http://www.outlinenone.com/ */

	/* Mobile tap highlight */
	/* https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-tap-highlight-color */
	html {
		-webkit-tap-highlight-color: rgba(128, 128, 128, 0.5);
	}

	/* === Scrollbars === */
/*
	::-webkit-scrollbar {
		@apply w-2;
	}
	::-webkit-scrollbar-track {
		@apply !bg-surface-50-900-token px-[1px];
	}
	::-webkit-scrollbar-thumb {
		@apply rounded-token bg-surface-400-500-token;
	}
*/

	/* Firefox */
	/* https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color#browser_compatibility */
/*	html {
		scrollbar-color: rgba(0, 0, 0, 0.2) rgba(255, 255, 255, 0.05);
	}
	html.dark {
		scrollbar-color: rgba(255, 255, 255, 0.1) rgba(0, 0, 0, 0.05);
	}
*/
	/* Hide Scrollbars */
	.hide-scrollbar::-webkit-scrollbar {
		display: none;
	}
	.hide-scrollbar {
		-ms-overflow-style: none; /* IE/Edge */
		scrollbar-width: none; /* Firefox */
	}

	/* === Horizontal Rules === */

	hr:not(.divider) {
		@apply block border-t border-solid border-surface-300-600-token;
	}
	.divider-vertical {
		@apply inline-block border-l border-solid border-surface-300-600-token min-h-[10px] mx-auto;
	}
}

/* Typographical Settings */
@import 'typography.css';

/* Imports all Tailwind Elements */
@import 'elements.css';

/* Imports all Variant Styles */
@import 'variants.css';
```
