### ISSUE TITLE
Themed Clear Buttons for Search Inputs

### ISSUE THREAD

**Issue by MrVauxs** [skeletonlabs/skeleton#1373]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

While a native implementation of browsers, the "X" button when a search input is focused often clashes with the themes, as shown in the examples below:
![image](https://user-images.githubusercontent.com/32039708/234404370-631adf9b-15a4-4310-a53f-51d9816d0694.png)
![image](https://user-images.githubusercontent.com/32039708/234404386-67e54c0e-0e33-47ef-9033-023c096237ea.png)
![image](https://user-images.githubusercontent.com/32039708/234404391-833bb288-ca3d-4d8e-b89c-46cb96f7656a.png)

The above being Chrome, but there's also Firefox and Mac:
![image](https://user-images.githubusercontent.com/32039708/234404451-fbd55d67-4b02-49e9-974f-98b712d53c05.png)
![image](https://user-images.githubusercontent.com/32039708/234404459-1cab5202-d2ca-4d71-9bd0-8ca0e966d1b4.png)

Figuring out how to style these or override such details would be great as some users find it a sore point to see a barely visible button in an otherwise neat looking UI.

### What type of pull request would this be?

Enhancement

### Any links to similar examples or other references we should review?

https://discord.com/channels/1003691521280856084/1100525820029714432/1100527141554241656

**Comment by endigo9740** [comment]
Thanks @MrVauxs. I'm copying your suggestion from the Discord convo over here so everything is one place:

```css
/* clears the ‘X’ from Internet Explorer */
input[type=search]::-ms-clear { display: none; width : 0; height: 0; }
input[type=search]::-ms-reveal { display: none; width : 0; height: 0; }
/* clears the ‘X’ from Chrome */
input[type="search"]::-webkit-search-decoration,
input[type="search"]::-webkit-search-cancel-button,
input[type="search"]::-webkit-search-results-button,
input[type="search"]::-webkit-search-results-decoration { display: none; }
```

I'll need to do some cross OS/browser testing to ensure this works as desired, but should provide a great starting place. Thanks!
