### ISSUE TITLE
Tokens do not support tw-opacity

### ISSUE THREAD

**Issue by PrisionMikeLime** [skeletonlabs/skeleton#2096]
### Current Behavior

When using `bg-primary-50-900-token` for example the code generated is:

```css
.dark .bg-primary-50-900-token {
    background-color: rgb(var(--color-primary-900));
}
.bg-primary-50-900-token {
    background-color: rgb(var(--color-primary-50));
}
.dark .bg-primary-50-900-token {
    background-color: rgb(var(--color-primary-900));
}
```

So using [tailwind opacity](https://v2.tailwindcss.com/docs/background-opacity) has no effect.

### Expected Behavior

Generated code should support tw opacity
```css
.dark .bg-primary-50-900-token {
    background-color: rgb(var(--color-primary-900) / var(--tw-text-opacity));
}
.bg-primary-50-900-token {
    background-color: rgb(var(--color-primary-50) / var(--tw-text-opacity));
}
.dark .bg-primary-50-900-token {
    background-color: rgb(var(--color-primary-900) / var(--tw-text-opacity));
}
```

### Steps To Reproduce

Simply use tailwind's opacity feature with a bg with token: ```class=`bg-primary-50-900-token bg-opacity-60` ```.

### More Information

I believe other uses of color might need to support transparency too.
