### ISSUE TITLE
Dual Range Slider

### ISSUE THREAD

**Issue by Silvallis** [skeletonlabs/skeleton#2224]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

A new type of range slider with two pips commonly used for price ranges (for example). 
![image](https://github.com/skeletonlabs/skeleton/assets/33603070/66fcf90c-f81e-4927-8784-4fe3b1721fe1)

This feature could either be an enhancement of the existing RangeSlider component or be a new component. 

I found this implementation of a dual range slider in pure HTML/CSS:
```html
<div class="range_container">
    <div class="sliders_control">
        <input id="fromSlider" type="range" value="10" min="0" max="100"/>
        <input id="toSlider" type="range" value="40" min="0" max="100"/>
    </div>
    <div class="form_control">
        <div class="form_control_container">
            <div class="form_control_container__time">Min</div>
            <input class="form_control_container__time__input" type="number" id="fromInput" value="10" min="0" max="100"/>
        </div>
        <div class="form_control_container">
            <div class="form_control_container__time">Max</div>
            <input class="form_control_container__time__input" type="number" id="toInput" value="40" min="0" max="100"/>
        </div>
    </div>
</div>
```
```css
.range_container {
  display: flex;
  flex-direction: column;
  width: 80%;
  margin: 35% auto;
}

.sliders_control {
  position: relative;
  min-height: 50px;
}

.form_control {
  position: relative;
  display: flex;
  justify-content: space-between;
  font-size: 24px;
  color: #635a5a;
}

input[type=range]::-webkit-slider-thumb {
  -webkit-appearance: none;
  pointer-events: all;
  width: 24px;
  height: 24px;
  background-color: #fff;
  border-radius: 50%;
  box-shadow: 0 0 0 1px #C6C6C6;
  cursor: pointer;
}

input[type=range]::-moz-range-thumb {
  -webkit-appearance: none;
  pointer-events: all;
  width: 24px;
  height: 24px;
  background-color: #fff;
  border-radius: 50%;
  box-shadow: 0 0 0 1px #C6C6C6;
  cursor: pointer;  
}

input[type=range]::-webkit-slider-thumb:hover {
  background: #f7f7f7;
}

input[type=range]::-webkit-slider-thumb:active {
  box-shadow: inset 0 0 3px #387bbe, 0 0 9px #387bbe;
  -webkit-box-shadow: inset 0 0 3px #387bbe, 0 0 9px #387bbe;
}

input[type="number"] {
  color: #8a8383;
  width: 50px;
  height: 30px;
  font-size: 20px;
  border: none;
}

input[type=number]::-webkit-inner-spin-button, 
input[type=number]::-webkit-outer-spin-button {  
   opacity: 1;
}

input[type="range"] {
  -webkit-appearance: none; 
  appearance: none;
  height: 2px;
  width: 100%;
  position: absolute;
  background-color: #C6C6C6;
  pointer-events: none;
}

#fromSlider {
  height: 0;
  z-index: 1;
}
```
![image](https://github.com/skeletonlabs/skeleton/assets/33603070/ac142d4e-771f-4f0a-a5d1-0aa6ef1cc4ad)

The biggest problem will be that there is no native option in the range input element, therefore it would need to be a custom option like the one provided.

### What type of pull request would this be?

New Feature

### Provide relevant links or additional information.

https://w3collective.com/double-range-slider-html-css-js/
https://medium.com/@predragdavidovic10/native-dual-range-slider-html-css-javascript-91e778134816
https://svelte.dev/repl/75d34e46cbe64bb68b7c2ac2c61931ce?version=4.2.2
https://codepen.io/predragdavidovic/pen/mdpMoWo
