### ISSUE TITLE
Invalid CSS generated by Tailwind plugin

### ISSUE THREAD

**Issue by maneac** [skeletonlabs/skeleton#2454]
### Current Behavior

Hi,

I'm trying to integrate Skeleton into a project that uses [LightningCSS](https://lightningcss.dev/) to process the final CSS output.
However, its strict CSS checking is unhappy with some of the generated selectors.

After a little digging, I believe the CSS generator is producing invalid selector(s):
```css
input[type='file']:not(.file-dropzone-input)::file-selector-button:disabled {
  cursor: not-allowed;
  opacity: 0.5;
}
```

### Expected Behavior

These selectors should be generated as:
```css
input[type='file']:not(.file-dropzone-input):disabled::file-selector-button {
  cursor: not-allowed;
  opacity: 0.5;
}
```

, based on the output from: https://play.tailwindcss.com/Icfyn4ryjG.

### Steps To Reproduce

Partial reproduction:
1. Run `pnpm -r build:jss` on a clean copy of this repository
2. Inspect `packages/plugin/src/tailwind/generated/generated-classes.js`.
Full reproduction:

`package.json`:
```json
{
    "name": "skeleton-issue",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
        "test": "tailwindcss -i test.css -o test.out.css"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "devDependencies": {
        "@skeletonlabs/tw-plugin": "^0.3.1",
        "tailwindcss": "^3.4.1"
    }
}
```

`tailwind.config.js`:
```js
import { skeleton } from "@skeletonlabs/tw-plugin";

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  theme: {
    extend: {},
  },
  plugins: [
    skeleton({
      themes: { preset: ["skeleton"] },
    }),
  ],
};
```

`test.css`
```css
@tailwind base;
@tailwind components;
```

Install, run the `test` script, and inspect `test.out.css` (or pass it into LightningCSS as an input).

### More Information

Thank you for producing a great component library!
