### ISSUE TITLE
Disabled state

### ISSUE THREAD

**Issue by bartduisters** [skeletonlabs/skeleton#2796]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

`cursor: not-allowed` is not default behavior for disabled elements (`cursor: default` is)

It is not compatible with `pointer-events: none` when applied on the same element.

If you do want both, you would always need to apply `cursor: not-allowed` on a wrapper/container element and have the children be `pointer-events: none`.

For default html elements like button and select, this can be done with an overwrite:
```css
:disabled {
  cursor: not-allowed;
}
:disabled > * {
  opacity: 0.5;
  pointer-events: none;
}
```

For Skeleton there probably needs to be a decision whether to follow browser defaults or apply `cursor: not-allowed` in a consistent way.

This ticket should be used to investigate it, the outcome would be a ticket to implement the consistency throughout the library.

### What type of pull request would this be?

Enhancement
