### ISSUE TITLE
iOS visual bug for Preview component gradient pattern

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#3279]
### Link to the Page

(any with a Preview component)

### Describe the Issue (screenshots encouraged!)

Seems to be an issue where there noisy background style does not match on iOS devices.

```css
.bg-noise {
	background-image: url('../images/noise-light.png');
	background-repeat: repeat;
	background-blend-mode: overlay;
}
```

| ios | desktop |
| -- | -- |
| ![Image](https://github.com/user-attachments/assets/095abb89-f6c9-4822-b16b-3642cde1dafa) | ![Image](https://github.com/user-attachments/assets/7d2a4c3d-2e55-4eff-a248-1c62e18bd0a8) |
