### ISSUE TITLE
tailwind: core styles only present in production builds and not development

### ISSUE THREAD

**Issue by nwrenger** [skeletonlabs/skeleton#3287]
### Current Behavior

When using a theme and applying the styling outlined in the documentation, the rendered page appears significantly different or somewhat broken. I've also recorded a Video:

https://github.com/user-attachments/assets/bae6c878-cb4f-4e9c-b639-048a044592da

### Expected Behavior

Styles working like in the docs.

### Steps To Reproduce

1. Setup like [outlined in the docs](https://next.skeleton.dev/docs/get-started/installation/sveltekit)
2. Add this to `app.css` and set style to `rose`:
```css
@import '@skeletonlabs/skeleton/themes/rose';

@layer base {
	html {
		@apply h-full;
	}
	body {
		background-attachment: fixed;
		background-image:
			radial-gradient(
				at 0% 25%,
				color-mix(in oklab, var(--color-primary-500) 10%, transparent) 0px,
				transparent 30%
			),
			radial-gradient(
				at 15% 6%,
				color-mix(in oklab, var(--color-success-500) 5%, transparent) 0px,
				transparent 30%
			);
		background-position: center;
		background-repeat: no-repeat;
		background-size: cover;
		overflow-x: hidden;
	}
}
```
3. Use this inside `+page.svelte`:
```svelte
<h1 class="h1">Welcome to SvelteKit</h1>
<p>
	Visit <a href="https://svelte.dev/docs/kit" class="anchor">svelte.dev/docs/kit</a> to read the documentation
</p>
<div
	class="card card-hover preset-filled-surface-100-900 border-surface-200-800 w-full max-w-md border-[1px] p-4 text-center"
>
	<p>Card</p>
</div>

<code class="code">
    This should be code styled
</code>
```

### Environment Information

  System:
    OS: macOS 15.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 158.36 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 23.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.9.0 - /opt/homebrew/bin/npm
    bun: 1.2.3 - ~/.bun/bin/bun
  Browsers:
    Safari: 18.3
  npmPackages:
    @skeletonlabs/skeleton: ^3.0.0-next.11 => 3.0.0-next.11 
    @skeletonlabs/skeleton-svelte: ^1.0.0-next.20 => 1.0.0-next.20
