### ISSUE TITLE
Add Tailwind component styles for `<mark>`

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#3407]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

It's an uncomment element but we should aim to support it for those that wish to use it. This should be a new `@utility` that is provided as an opt-in class per our usual paradigms. I'd suggest the default be the `tertiary` color as it's intended to contrast.

```html
<mark class="mark">Some text here</mark>
```

```css
@utility mark {
  background-color: var(--color-tertiary-500);
  background-color: var(--radius-sm);
}
```

Make sure to add a documentation page covering the usage similar to MDN (linked below).

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark
