### ISSUE TITLE
Fix color parings on Skeleton Core playground app

### ISSUE THREAD

**Issue by endigo9740** [skeletonlabs/skeleton#3447]
### Link to the Page

Playgrounds -> Skeleton-Core -> `/design/colors`

### Describe the Issue (screenshots encouraged!)

Not sure what's up with this, but this should always work when referencing the raw theme properties with `var()` as those properties should always be in scope, unlike Tailwind classes that may or may not be in the CSS bundle.

Here's an example of how this is set:

```html
<div style={`background: var(--color-${name}-${light}-${dark})`}>...</div>
```

![Image](https://github.com/user-attachments/assets/2b6c6671-17ff-483b-83c1-184e002a8e41)

**Comment by nasheomirro** [comment]
From experimenting, it seems tailwind will remove even custom variables which are not referenced with `var()` on any of the classes it recognizes. And despite tailwind not recognizing most of the color variables, those variables still exist because of the imported theme, but the theme doesn't include pairings since those variables are exclusively made with tailwind.

the `primary` pairings exist because it's being used in `designs/presets`, same with the other colors because of the `preset-tonal-*` classes and the `surface` pairings are being used in other places.

**Comment by endigo9740** [comment]
Interesting @nasheomirro, I knew this was the case with unused utility classes - but very odd to hear this happens for CSS properties as well. Does it seem this only happens for properties defined in `@theme inline`? Because I see you're still dynamically constructing properties from `@theme` in your PR. You're essentially recreating the color pairings typically implemented via the `inline` set. Totally fine if that works, but I'm curious what the distinction is here.

**Comment by nasheomirro** [comment]
Nope, tailwind targets all variables defined inside `@theme` except for variables defined with[`@theme static`](https://tailwindcss.com/docs/theme#generating-all-css-variables). I'm actually taking advantage of the existing color variables defined in `data-theme="cerberus"` since tailwind doesn't touch those, that's why the color palette section works even though it's also dynamically constructed.

It's a bit weird cause I assumed tailwind would leave custom `@theme` variables alone but in retrospect it makes sense. One odd behavior is that unlike classes, it has a different way of deciding which variables are removed:
```css

/* works if any custom CSS uses the variable */
body {
  color: var(--color-surface-950-50);
}

/* works if the utility `foo` is used anywhere */
@utility foo {
  color: var(--color-primary-500);
}

/* it also works in arbitrary classes */
const foo = "bg-[var(--color-primary-500)]"
<div class="bg-[var(--color-secondary-100-900)]"></div>

/* doesn't work if used anywhere else, the variable still gets removed */
const foo = "var(--color-secondary-100-900)";
<div style="color: var(--color-secondary-100-900)"></div>
```

Anyways, if we really want the theme variables to exist without getting pruned we could use `@theme static` in the `skeleton` package itself.
