### ISSUE TITLE
Theme background examples should target `<body>`

### ISSUE THREAD

**Issue by Cikmo** [skeletonlabs/skeleton#3464]
### Link to the Page

https://www.skeleton.dev/docs/design/themes#backgrounds

### Describe the Issue (screenshots encouraged!)

Because `data-theme` has been moved to the `<html>` element, to apply background images to the body you need to target it explicitly:

```css
[data-theme='cerberus'] {
	& body {
		background-image:
			radial-gradient(at 24% 25%, color-mix(in oklab, var(--color-primary-500) 30%, transparent) 0px, transparent 30%),
			radial-gradient(at 35% 13%, color-mix(in oklab, var(--color-success-500) 18%, transparent) 0px, transparent 30%),
			radial-gradient(at 100% 64%, color-mix(in oklab, var(--color-error-500) 3%, transparent) 0px, transparent 40%);
		background-attachment: fixed;
		background-position: center;
		background-repeat: no-repeat;
		background-size: cover;
	}
}
```
