### ISSUE TITLE
`text-on-X-token` isn't respected inside `alert` containers in dark-mode

### ISSUE THREAD

**Issue by AgarwalPragy** [skeletonlabs/skeleton#894]
### Current Behavior

light-mode
<img width="394" alt="image" src="https://user-images.githubusercontent.com/7423639/215286310-0fc82f81-ef35-4625-b0a0-b704688d68ae.png">

dark-mode
<img width="392" alt="image" src="https://user-images.githubusercontent.com/7423639/215286300-5d74f768-c774-4422-87a0-8cbd31345a8e.png">

### Steps To Reproduce

Use the skeleton theme, and turn on dark-mode

```html
<aside class="alert variant-filled-warning">
    <h3 class="alert-message">Warning</h3>
</aside>
```

### Anything else?

It seems that `.dark .variant-filled-warning` doesn't set the text-color.

```css
.dark .variant-filled-warning {
    --tw-bg-opacity: 1;
    background-color: rgb(var(--color-warning-500) / var(--tw-bg-opacity));

    /* Note that `color` is missing */
}

.variant-filled-warning {
    --tw-bg-opacity: 1;
    background-color: rgb(var(--color-warning-500) / var(--tw-bg-opacity));
    color: rgb(var(--on-warning));
}
```

This causes `.dark .alert` to override the text color
```css
.dark .alert {
    color: rgb(var(--color-surface-50));
}
```
